Vagrant.configure(2) do |config|

  config.vm.define "vm1" do |c|
    c.vm.network :private_network, ip: "192.168.13.11"
    c.vm.box = "centos/7"
  end

  config.vm.define "vm2" do |c|
    c.vm.network :private_network, ip: "192.168.13.12"
    c.vm.box = "ubuntu/trusty64"
  end

end
