---
- name: Converge
  hosts: all
  gather_facts: False
  become: yes
  tasks:
    - name: Install python for Ansible
      raw: test -e /usr/bin/python || (apt -y update && apt install -y python-minimal)
      become: True
      changed_when: False

- name: Converge
  hosts: all
  become: yes
  roles:
    - role: ansible-hosts
